name: Java CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Compile and Test
        run: |
          javac -cp .:junit-platform-console-standalone.jar *.java
          java -jar junit-platform-console-standalone.jar --class-path . --scan-class-path
